name: Update Submodules

on:
  schedule:
    - cron: '0 9 * * 1' # Every Monday at 9 AM UTC
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: write
  pull-requests: write

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      
      - name: Update submodules (allow unrelated histories)
        run: |
          git submodule update --remote --merge --allow-unrelated-histories
      
      - name: Check for changes
        id: changes
        run: |
          if git diff --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "Changes detected in submodules:"
            git diff --name-only
          fi
      
      - name: Create Pull Request
        if: steps.changes.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update submodules to latest versions"
          title: "🔄 Update Submodules"
          body: |
            ## Automated Submodule Update
            
            This PR updates all submodules to their latest versions.
            
            ### Changes
            - Updated submodules to latest commits from their respective main branches
            
            ### Auto-generated by GitHub Actions
            - Workflow: `update-submodules.yml`
            - Triggered: Weekly schedule (Mondays 9 AM UTC)
          branch: update-submodules
          delete-branch: true
          labels: |
            dependencies
            submodules
            automated
